### ISSUE TITLE
Expected Time of Multiple Lines for one graph?

### ISSUE THREAD

**Issue by ayuk23** [Boris-Em/BEMSimpleLineGraph#125]
Hey I love your library and your graphs are amazing. I would like to use them, however my team needs to be able to have multiple lines displayed for one graph. Is there an ETA for this feature? I've considered implementing it myself, but I'd rather not if its close to being finished.

Thanks!

**Comment by Boris-Em** [comment]
Hi @ayuk23,
Thanks for the encouraging words about BEMSimpleLineGraph.
Unfortunately I really can't spend much time working on the library lately because things at work are really busy =\
I wouldn't expect this feature to be done anytime soon (at least not by me).
Having said that, you might want to take a look at @adonishi's work on this PR #108.
I haven't been able to review it, but it seems promising.
Please keep us updated and create a PR if you make any work for this feature.
