### ISSUE TITLE
Sometimes a line draws twice

### ISSUE THREAD

**Issue by dkk** [Boris-Em/BEMSimpleLineGraph#220]
with the BEMLineAnimationDraw it seems that it draws forth and back. 

Happens by setting f.e. lineDashPatternForReferenceXAxisLines = @[@(7),@(3)];

In this image, it is the line at 242:
![line drawn twice](https://cloud.githubusercontent.com/assets/576723/9008305/9458f4f2-3799-11e5-9dd3-7fb2557e2106.png)

**Comment by Knodd** [comment]
After a lot of testing and googling I found the problem!
Comment out all lines containing "closePath" in BEMLine.m
Making [verticalReferenceLinesPath closePath]; become //[verticalReferenceLinesPath closePath]; and so on.

From Apple docs: 
The processes for building and using a path object are separate. Building the path is the first process and involves the following steps:
1. Create the path object.
2. Set any relevant drawing attributes of your UIBezierPath object, such as the lineWidth or lineJoinStyle properties for stroked paths or the usesEvenOddFillRule property for filled paths. These drawing attributes apply to the entire path.
3. Set the starting point of the initial segment using the moveToPoint: method.
4. Add line and curve segments to define a subpath.
**5. Optionally, close the subpath by calling closePath, which draws a straight line segment from the end of the last segment to the beginning of the first.**
6. Optionally, repeat the steps 3, 4, and 5 to define additional subpaths.

https://developer.apple.com/library/ios/documentation/2DDrawing/Conceptual/DrawingPrintingiOS/BezierPaths/BezierPaths.html

Since reference lines is not a closed object, closing is obsolete

**Comment by Sam-Spencer** [comment]
Thanks to @dkk for pointing this out, and a special thanks to @Knodd for taking the time to suggest a fix!  Checkout the latest commit for a fix!
