### ISSUE TITLE
XAxisLabel

### ISSUE THREAD

**Issue by kongfanwu** [Boris-Em/BEMSimpleLineGraph#264]
BOOL fullyContainsLabel = CGRectContainsRect(self.bounds, label.frame);
    if (!fullyContainsLabel) {
        [overlapLabels addObject:label];
    }

CGRectContainsRect Always return NO cause
 > (lldb) po NSLog(@"%d", CGRectContainsRect(CGRectMake(0, 0, 355, 250),  
 > CGRectMake(51.373999999999995, 234.66000000000003, 14.456, 15.34)));  
 > 2016-05-24 16:55:17.802 XLoongGlass[30684:19026720] 0  
 > (lldb) po NSLog(@"%d", CGRectContainsRect(CGRectMake(0, 0, 355, 250), CGRectMake(51.374, 234.66, 14.456, 15.34)));  
 > 2016-05-24 16:55:23.676 XLoongGlass[30684:19026720] 1

**Comment by Boris-Em** [comment]
Hi @kongfanwu,
Could you please format your message? You can take a look at [this guide](https://guides.github.com/features/mastering-markdown/) if you're not familiar with Markdown. Thanks!

**Comment by zero0cool0** [comment]
I'd like this issue to be reopened please. I'm tracking a bug in my app where `fullyContainsLabel` is always FALSE.

I believe the issue is in `label.frame` where `y+height` is marginally bigger than 167.

`
(lldb) po self.bounds
(origin = (x = 0, y = 0), size = (width = 1072, height = 167))

(lldb) po label.frame
(origin = (x = 876.0060512820512, y = 151.66000000000003), size = (width = 14.456, height = 15.34))
`
