### ISSUE TITLE
Graph not working in iOS 10

### ISSUE THREAD

**Issue by sbnair** [Boris-Em/BEMSimpleLineGraph#276]
Hi

   Please help, i am not able to see graph in iOS 10 which i downloaded latest, please let me know how it can be fixed and what is the issue.

Thanks,
Shaliest.

**Comment by Sam-Spencer** [comment]
Hi @sbnair, BEMSimpleLineGraph works out of the box with iOS 10 and Xcode 8. Please [ask your question on StackOverflow using the `bemsimplelinegraph` tag](http://stackoverflow.com/questions/tagged/bemsimplelinegraph). Make sure to provide details with your question so that the StackOverflow community can help you out.
