### ISSUE TITLE
gradientBottom potential leak

### ISSUE THREAD

**Issue by CatchZeng** [Boris-Em/BEMSimpleLineGraph#277]
![2016-10-06 8 27 52](https://cloud.githubusercontent.com/assets/10027281/19136387/df9dad54-8b9e-11e6-9afa-b603d1830fc6.png)

**Comment by Sam-Spencer** [comment]
Hi @CatchZeng, thanks for taking the time to point this out. I tested the project and looked at the analysis... while it appears that the sample project's view controller might be leaking its gradient object here, releasing it while still in the scope of `viewDidLoad:` causes a crash when the graph attempts to draw itself (because it may not begin drawing until after `viewDidLoad:` finishes). At this point, I wouldn't worry about it too much; its more of an issue with the sample project implementation than the graph itself.

Thank you for the feedback! It's really appreciated!
