### ISSUE TITLE
X-Axis labels clipped at graph edges

### ISSUE THREAD

**Issue by hamesetawa** [Boris-Em/BEMSimpleLineGraph#67]
The X-axis labels are cut off... so show them vertically? Or can you get them to not be cut off?

**Comment by brightsider** [comment]
I'm fix it via adding this after settings the center of label:
rect = labelXAxis.frame;
if (rect.origin.x < self.YAxisLabelXOffset)
   rect.origin.x = self.YAxisLabelXOffset;
if (CGRectGetMaxX(rect) > CGRectGetMaxX(self.frame))
   rect.origin.x -= (CGRectGetMaxX(rect) - CGRectGetMaxX(self.frame));
labelXAxis.frame = rect;

**Comment by ilandbt** [comment]
Why is this issue closed? i still have this problem.
How can i fix it
Thanks

**Comment by Sam-Spencer** [comment]
The latest commit, 64b4fb1, should (FINALLY!! :joy: :tada:) fix this issue! The x-axis label values are now calculated like the dots and the fringe labels get additional horizontal padding added to them. This extra padding is negated on the vertical reference lines (in order to keep them in their correct positions). Plus, the padding is dynamic, so there's no guess work with arbitrary values and auto layout. 

Hope everyone finds the fix useful and beneficial! Cheers!

**Comment by Yita55** [comment]
![2016-01-18 2 58 12](https://cloud.githubusercontent.com/assets/3118774/12385184/3acf8644-bdf4-11e5-97e1-369b11df863b.png)
